/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example_zhangjunling_com_ndk_hellowork_BionicActivity */

#ifndef _Included_example_zhangjunling_com_ndk_hellowork_BionicActivity
#define _Included_example_zhangjunling_com_ndk_hellowork_BionicActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example_zhangjunling_com_ndk_hellowork_BionicActivity
 * Method:    processInteractoin
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_example_zhangjunling_com_ndk_1hellowork_BionicActivity_processInteractoin
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
