/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example_zhangjunling_com_ndk_hellowork_DebugActivity */

#ifndef _Included_example_zhangjunling_com_ndk_hellowork_DebugActivity
#define _Included_example_zhangjunling_com_ndk_hellowork_DebugActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example_zhangjunling_com_ndk_hellowork_DebugActivity
 * Method:    helloWordBreadDown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_example_zhangjunling_com_ndk_1hellowork_DebugActivity_helloWordBreadDown
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
