/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example_zhangjunling_com_ndk_hellowork_ExceptionJniActivity */

#ifndef _Included_example_zhangjunling_com_ndk_hellowork_ExceptionJniActivity
#define _Included_example_zhangjunling_com_ndk_hellowork_ExceptionJniActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example_zhangjunling_com_ndk_hellowork_ExceptionJniActivity
 * Method:    exceptionHelloWord
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_example_zhangjunling_com_ndk_1hellowork_ExceptionJniActivity_exceptionHelloWord
        (JNIEnv *, jobject);

/*
 * Class:     example_zhangjunling_com_ndk_hellowork_ExceptionJniActivity
 * Method:    doExceptionTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_example_zhangjunling_com_ndk_1hellowork_ExceptionJniActivity_doExceptionTest
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
