/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example_zhangjunling_com_ndk_hellowork_HelloWordJniActivity */

#ifndef _Included_example_zhangjunling_com_ndk_hellowork_HelloWordJniActivity
#define _Included_example_zhangjunling_com_ndk_hellowork_HelloWordJniActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example_zhangjunling_com_ndk_hellowork_HelloWordJniActivity
 * Method:    getStringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_example_zhangjunling_com_ndk_1hellowork_HelloWordJniActivity_getStringFromJni
        (JNIEnv *, jobject);

/*
 * Class:     example_zhangjunling_com_ndk_hellowork_HelloWordJniActivity
 * Method:    operatorData
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_example_zhangjunling_com_ndk_1hellowork_HelloWordJniActivity_operatorData
        (JNIEnv *, jobject, jstring);

/*
 * Class:     example_zhangjunling_com_ndk_hellowork_HelloWordJniActivity
 * Method:    getIntArrayFromJni
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_example_zhangjunling_com_ndk_1hellowork_HelloWordJniActivity_getIntArrayFromJni
        (JNIEnv *, jobject);

/*
 * Class:     example_zhangjunling_com_ndk_hellowork_HelloWordJniActivity
 * Method:    setIntArrayToJni
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_example_zhangjunling_com_ndk_1hellowork_HelloWordJniActivity_setIntArrayToJni
        (JNIEnv *, jobject, jintArray);

/*
 * Class:     example_zhangjunling_com_ndk_hellowork_HelloWordJniActivity
 * Method:    getRegionArrayFromJin
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_example_zhangjunling_com_ndk_1hellowork_HelloWordJniActivity_getRegionArrayFromJin
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
