/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example_zhangjunling_com_ndk_hellowork_HelloWordJniActivity */

#ifndef _Included_example_zhangjunling_com_ndk_hellowork_HelloWordJniActivity
#define _Included_example_zhangjunling_com_ndk_hellowork_HelloWordJniActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example_zhangjunling_com_ndk_hellowork_HelloWordJniActivity
 * Method:    getStringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_example_zhangjunling_com_ndk_1hellowork_HelloWordJniActivity_getStringFromJni
        (JNIEnv *, jobject);

/*
 * Class:     example_zhangjunling_com_ndk_hellowork_HelloWordJniActivity
 * Method:    operatorData
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_example_zhangjunling_com_ndk_1hellowork_HelloWordJniActivity_operatorData
        (JNIEnv *, jobject, jstring);

/*
 * Class:     example_zhangjunling_com_ndk_hellowork_HelloWordJniActivity
 * Method:    getIntArrayFromJni
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_example_zhangjunling_com_ndk_1hellowork_HelloWordJniActivity_getIntArrayFromJni
        (JNIEnv *, jobject);

/*
 * Class:     example_zhangjunling_com_ndk_hellowork_HelloWordJniActivity
 * Method:    setIntArrayToJni
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_example_zhangjunling_com_ndk_1hellowork_HelloWordJniActivity_setIntArrayToJni
        (JNIEnv *, jobject, jintArray);

/*
 * Class:     example_zhangjunling_com_ndk_hellowork_HelloWordJniActivity
 * Method:    getRegionArrayFromJin
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_example_zhangjunling_com_ndk_1hellowork_HelloWordJniActivity_getRegionArrayFromJin
        (JNIEnv *, jobject);

/*
 * Class:     example_zhangjunling_com_ndk_hellowork_HelloWordJniActivity
 * Method:    getDirectByteBufferFromJni
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_example_zhangjunling_com_ndk_1hellowork_HelloWordJniActivity_getDirectByteBufferFromJni
        (JNIEnv *, jobject);

/*
 * Class:     example_zhangjunling_com_ndk_hellowork_HelloWordJniActivity
 * Method:    setDirectByteBufferToJni
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_example_zhangjunling_com_ndk_1hellowork_HelloWordJniActivity_setDirectByteBufferToJni
        (JNIEnv *, jobject, jobject);

/*
 * Class:     example_zhangjunling_com_ndk_hellowork_HelloWordJniActivity
 * Method:    getJavaFieldString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_example_zhangjunling_com_ndk_1hellowork_HelloWordJniActivity_getJavaFieldString
        (JNIEnv *, jobject);

/*
 * Class:     example_zhangjunling_com_ndk_hellowork_HelloWordJniActivity
 * Method:    setJavaFieldString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_example_zhangjunling_com_ndk_1hellowork_HelloWordJniActivity_setJavaFieldString
        (JNIEnv *, jobject);

/*
 * Class:     example_zhangjunling_com_ndk_hellowork_HelloWordJniActivity
 * Method:    getJavaStaticFieldString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_example_zhangjunling_com_ndk_1hellowork_HelloWordJniActivity_getJavaStaticFieldString
        (JNIEnv *, jobject);

/*
 * Class:     example_zhangjunling_com_ndk_hellowork_HelloWordJniActivity
 * Method:    setJavaStaticFieldString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_example_zhangjunling_com_ndk_1hellowork_HelloWordJniActivity_setJavaStaticFieldString
        (JNIEnv *, jobject);

/*
 * Class:     example_zhangjunling_com_ndk_hellowork_HelloWordJniActivity
 * Method:    callFieldMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_example_zhangjunling_com_ndk_1hellowork_HelloWordJniActivity_callFieldMethod
        (JNIEnv *, jobject);

/*
 * Class:     example_zhangjunling_com_ndk_hellowork_HelloWordJniActivity
 * Method:    callStaticMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_example_zhangjunling_com_ndk_1hellowork_HelloWordJniActivity_callStaticMethod
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
